import { Ontmoetingsplek } from "./types";

export const mockPlekken: Ontmoetingsplek[] = [
  {
    id: "1",
    naam: "Wijkcentrum Helftheuvel",
    beschrijving:
      "Wijkcentrum Helftheuvel is het kloppende hart van West. Hier vinden allerlei activiteiten plaats voor bewoners van alle leeftijden: van yogalessen en schildercursussen tot informatiebijeenkomsten en buurtborrels.",
    adres: "Kraaivenstraat 2, 5213 LE 's-Hertogenbosch",
    lat: 51.696,
    lng: 5.288,
    buurt: "Kruiskamp",
    type: "buurtgericht",
    doelgroepen: ["inwoners", "ouderen", "gezinnen"],
    contact_telefoon: "073-123 45 67",
    contact_email: "info@helftheuvel.nl",
    contact_website: "https://www.helftheuvel.nl",
    openingstijden: "Ma–vr: 9:00–21:00 | Za: 10:00–17:00",
    actief: true,
    created_at: "2024-01-01",
  },
  {
    id: "2",
    naam: "Buurthuis De Schutskamp",
    beschrijving:
      "Een laagdrempelige ontmoetingsplek midden in de Schutskamp. Buurthuis De Schutskamp organiseert regelmatig buurtactiviteiten en biedt ruimte aan lokale initiatieven en bewonersgroepen.",
    adres: "Schutskampweg 10, 5216 HB 's-Hertogenbosch",
    lat: 51.7025,
    lng: 5.2895,
    buurt: "Schutskamp",
    type: "buurtgericht",
    doelgroepen: ["inwoners", "ouderen", "gezinnen"],
    contact_telefoon: "073-234 56 78",
    contact_email: "contact@buurthuis-schutskamp.nl",
    openingstijden: "Di en do: 10:00–16:00 | Za: 11:00–15:00",
    actief: true,
    created_at: "2024-01-02",
  },
  {
    id: "3",
    naam: "Kinderboerderij West",
    beschrijving:
      "Een gezellige kinderboerderij waar kinderen en hun ouders in contact komen met dieren en de natuur. Naast de dieren zijn er regelmatig educatieve activiteiten en workshops voor kinderen.",
    adres: "Deuterseweg 15, 5215 MH 's-Hertogenbosch",
    lat: 51.7018,
    lng: 5.301,
    buurt: "Deuteren",
    type: "buurtgericht",
    doelgroepen: ["kinderen", "gezinnen", "inwoners"],
    contact_telefoon: "073-345 67 89",
    contact_email: "info@kinderboerderijwest.nl",
    openingstijden: "Di–zo: 10:00–17:00",
    actief: true,
    created_at: "2024-01-03",
  },
  {
    id: "4",
    naam: "Jongerencentrum De Pit",
    beschrijving:
      "Jongerencentrum De Pit is de plek voor jongeren in West. Hier kunnen ze terecht voor vrije inloop, sport en spelactiviteiten, huiswerkbegeleiding en tal van cursussen en workshops.",
    adres: "Kruiskampplein 5, 5213 NK 's-Hertogenbosch",
    lat: 51.6948,
    lng: 5.287,
    buurt: "Kruiskamp",
    type: "complexgericht",
    doelgroepen: ["jongeren"],
    contact_telefoon: "073-456 78 90",
    contact_email: "depit@jongerenwerk073.nl",
    contact_website: "https://www.jongerenwerk073.nl",
    openingstijden: "Ma–vr: 15:00–21:00 | Za: 13:00–19:00",
    actief: true,
    created_at: "2024-01-04",
  },
  {
    id: "5",
    naam: "Ruilwinkel West",
    beschrijving:
      "Bij Ruilwinkel West kun je gratis spullen brengen en meenemen. Kleding, boeken, speelgoed, huishoudelijke artikelen — alles is welkom. Een mooie plek om elkaar te ontmoeten en samen duurzamer te leven.",
    adres: "Schutskampstraat 22, 5216 HC 's-Hertogenbosch",
    lat: 51.703,
    lng: 5.288,
    buurt: "Schutskamp",
    type: "buurtgericht",
    doelgroepen: ["inwoners", "gezinnen"],
    contact_email: "ruilwinkelwest@gmail.com",
    openingstijden: "Za: 10:00–13:00",
    actief: true,
    created_at: "2024-01-05",
  },
  {
    id: "6",
    naam: "GGD & MEE Zorgpunt West",
    beschrijving:
      "Het gezamenlijke zorgpunt van GGD Hart voor Brabant en MEE Brabant biedt laagdrempelige ondersteuning op het gebied van gezondheid, welzijn en participatie. Professionals en inwoners kunnen hier terecht voor advies en doorverwijzing.",
    adres: "Deuterseweg 45, 5215 ML 's-Hertogenbosch",
    lat: 51.7015,
    lng: 5.3025,
    buurt: "Deuteren",
    type: "buurtgericht",
    doelgroepen: ["inwoners", "professionals"],
    contact_telefoon: "073-567 89 01",
    contact_email: "zorgpuntwest@ggdhvb.nl",
    openingstijden: "Ma–vr: 8:30–17:00",
    actief: true,
    created_at: "2024-01-06",
  },
  {
    id: "7",
    naam: "Dorpshuis Engelen",
    beschrijving:
      "Het dorpshuis van Engelen is het centrum van het gemeenschapsleven in dit groene deel van West. Hier vinden dorpsactiviteiten, vergaderingen van de wijkraad en diverse clubs en verenigingen hun thuis.",
    adres: "Engelseweg 8, 5221 AC 's-Hertogenbosch",
    lat: 51.7205,
    lng: 5.279,
    buurt: "Engelen",
    type: "complexgericht",
    doelgroepen: ["inwoners", "ouderen", "gezinnen"],
    contact_telefoon: "073-678 90 12",
    contact_email: "dorpshuisengelen@gmail.com",
    openingstijden: "Activiteiten afhankelijk van planning, zie website",
    actief: true,
    created_at: "2024-01-07",
  },
  {
    id: "8",
    naam: "Buurtmoestuin Deuteren",
    beschrijving:
      "In de buurtmoestuin Deuteren kunnen bewoners een eigen tuinbed huren. Naast tuinieren is het een plek voor ontmoeting, uitwisseling van kennis en gezamenlijke activiteiten rondom gezond voedsel en duurzaamheid.",
    adres: "Deuterseweg 30, 5215 MJ 's-Hertogenbosch",
    lat: 51.702,
    lng: 5.3018,
    buurt: "Deuteren",
    type: "buurtgericht",
    doelgroepen: ["inwoners", "ouderen", "gezinnen"],
    contact_email: "moestuindeuteren@gmail.com",
    openingstijden: "Altijd toegankelijk voor huurders",
    actief: true,
    created_at: "2024-01-08",
  },
  {
    id: "9",
    naam: "Moskee Al-Fourqaan",
    beschrijving:
      "Moskee Al-Fourqaan vervult een belangrijke sociale rol in West. Naast religieuze diensten organiseert de moskee maatschappelijke activiteiten, taalcursussen en ontmoetingen die bijdragen aan verbinding tussen culturen in de wijk.",
    adres: "Schutskampweg 18, 5216 HB 's-Hertogenbosch",
    lat: 51.7022,
    lng: 5.29,
    buurt: "Schutskamp",
    type: "complexgericht",
    doelgroepen: ["inwoners", "gezinnen"],
    contact_telefoon: "073-789 01 23",
    contact_email: "info@alfourqaan.nl",
    openingstijden: "Dagelijks open voor gebed en activiteiten",
    actief: true,
    created_at: "2024-01-09",
  },
  {
    id: "10",
    naam: "Speeltuin De Ster",
    beschrijving:
      "Speeltuin De Ster is een heerlijke buitenspeelplek voor kinderen tot 12 jaar. Met klimrekken, schommels, zandbak en een waterpartij is het een populaire ontmoetingsplek voor gezinnen in de Kruiskamp.",
    adres: "Kruiskampstraat 12, 5213 NE 's-Hertogenbosch",
    lat: 51.6965,
    lng: 5.2865,
    buurt: "Kruiskamp",
    type: "buurtgericht",
    doelgroepen: ["kinderen", "gezinnen"],
    contact_email: "speeltuinder@gmail.com",
    openingstijden: "April–oktober: dagelijks 10:00–18:00",
    actief: true,
    created_at: "2024-01-10",
  },
];
